databases:
  - name: car.end
    databaseName: car_end
    user: car_end_user

services:
  - type: web
    name: car.end
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car.end
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
